// scripts/categorize/rules.js
//
// Reglas determinísticas para CF-CATEGORÍAS-1 — separadas de la ejecución
// (classify.js las consume, run.js decide cuándo reclasificar). Versionar
// RULES_VERSION cada vez que se cambien listas de autores/keywords/objetos:
// run.js usa esta versión (junto con TAXONOMY_VERSION) para decidir si un
// registro ya clasificado necesita reclasificarse.
//
// Origen de los datos: MINED_AUTHOR_SIGNALS se extrajo programáticamente de
// los ~600 casos clasificados a mano en las sesiones CF-CATEGORÍAS-0B y 0C
// (autor real -> categoría real, revisado uno por uno, no adivinado). Los
// autores genéricos ("VV. AA.", "Varios autores", "Sin Autor", etc., que
// aparecían repetidos en categorías distintas) se filtraron antes de esta
// exportación porque no son una señal útil.

export const RULES_VERSION = 14;

export const MINED_AUTHOR_SIGNALS = {
  "esoterismo-tarot": {
    "authors": [
      "AIGUA DE VALENCIA",
      "ALANA FAIRCHILD ; ISABEL BRYNA",
      "ANNE STOKES",
      "Aldo Lavagnini",
      "Alice Bailey",
      "Aryeh Kaplan",
      "Astromostra",
      "Benitez, J. J.",
      "Blake, Deborah",
      "Bulard-Cordeau, Brigitte",
      "CONNY MENDEZ",
      "Café, Sônia",
      "Ciro Marchetti",
      "DARCEY, CHERALYN",
      "Dass, Ram",
      "Doreen Virtue",
      "EDUARDO MADIROLAS",
      "FOURNIER",
      "Gabriel Silva",
      "Graciela Iriondo",
      "H.P. Blavatsky",
      "Hawkins, David",
      "IÑIGUEZ PUEBLA, AFRICA",
      "J. A. Portela",
      "J.J. Benítez",
      "JOHN MATTEWS",
      "LO SCARABEO",
      "LUCY CAVENDISH",
      "Leaping Hare",
      "Lisa Parker",
      "MARCHETTI , FRANCISCO A. ³ ESCUELA DE CABALA DE MARIO SABAN",
      "Mabel Collins",
      "Monika Correia Nobre",
      "Omar Hejeile",
      "ROBERTO DE ANGELIS",
      "STOPFORTH, BUTLER",
      "SWAMI SRI YUKTESWAR",
      "Salerno Toni Carmine",
      "Travis McHenry",
      "Vanesa Maiorana",
      "Yoshi Yoshitani",
      "Rebecca Campbell",
      "Campbell, Rebecca",
      "Rav Berg",
      "Idries Shah",
      "Shah, Idries",
      "Mario Javier Saban",
      "Saban, Mario Javier",
      "SABAN MARIO JAVIER",
      "Franz Bardon",
      "Benny Hinn",
      "Hinn, Benny",
      "C. W. Leadbeater",
      "LEADBEATER, C. W."
    ],
    "publishers": [
      "Da Brigh",
      "LENORMAND",
      "Lo Scarabeo",
      "Oberon",
      "Rockpool Publishing",
      "Tarot"
    ]
  },
  "arte-diseno-fotografia": {
    "authors": [
      "3dtotal Publishing",
      "Akira D Tobirama",
      "Byrne, David",
      "Caldas, Sara",
      "Cruz Delgado Sánchez",
      "Czerny, Carl",
      "DAVID ABDREU BACH",
      "DENNIC CHUNMAN LO",
      "ENRIC JARDI",
      "Harry, Debbie",
      "JAMES BASTIEN",
      "JAN SWAFFORD",
      "MOY SANTANA, ANTONIO JOSE ALBERTOS",
      "Mario Pons Sansegundo",
      "Oasis",
      "Smith, Keri",
      "Violeta Hemsy de Gainza"
    ],
    "publishers": []
  },
  "educacion": {
    "authors": [
      "Alicia Oiberman",
      "Anya Damiron y Pablo Pino",
      "BEATRIZ ACTIS (Comp.)",
      "Brailovsky, Daniel",
      "Cañeque, Hilda",
      "DOLORS OLIVER AGÜERA",
      "Duvouldy, Marine",
      "Faber, Adele",
      "Grunfeld, Diana",
      "Grunin, Julián",
      "Harf, Ruth",
      "Howard Gardner",
      "JOSÉ MARTÍNEZ ROMERO",
      "Klara Moncho",
      "Laura Pitluk",
      "Liliana Gruss / Francis Rosemberg",
      "MON ESPINOSA",
      "Malajovich, Ana",
      "Mariana Morales y Juan Fernandez",
      "Miller, Alice",
      "Monica Coronado",
      "PAOLA DOGLIOTTI MORO",
      "Priscilla Vela, Mercedes Herran, Priscilla Vela, Mercedes Herran",
      "Pujato, Beatriz",
      "Romero, Claudia Compiladora",
      "SKINNER, Gary & OTHERS",
      "Stanislas Dehaene",
      "TERRITORIOS DE JUEGO Y EXPLORACION",
      "Valeria Abusamra",
      "Wagnon, Sylvain"
    ],
    "publishers": [
      "Neuroaprendizaje"
    ]
  },
  "religion-espiritualidad": {
    "authors": [
      "American Bible Society",
      "Anthony De Mello",
      "Ariel Álvarez Valdes",
      "B&H Español",
      "Bernard Hurault",
      "Celam",
      "David Wilkerson",
      "Descleé de Brouwer",
      "Ediciones san Pablo",
      "Editorial Vida",
      "Elena G. de White",
      "FRANZ JALICS",
      "Francesco Castelli",
      "Francisco Cantera Burgos;Manuel Iglesias González",
      "Instituto Fe y Vida",
      "John MacArthur",
      "Lecturas Dr. George Guthrie",
      "Madre Teresa de Calcuta",
      "MADRE TERESA DE CALCUTA, NúRIA PUJOL VALLS, MADRE TERESA DE CALCUTA, NúRIA PUJOL VALLS",
      "Núñez, Miguel",
      "Paramahansa Yogananda",
      "Papa León XIV",
      "PAPA LEON XIV",
      "Ratzinger Joseph, Benedicto XVI",
      "Sarah Young",
      "Young, Sarah",
      "Silva Retamales, Santiago",
      "Pedro I. Fraile Yécora",
      "Pedro I. Fraile",
      "Rabi Najman De Breslov",
      "Francesc Ramis Darder",
      "Prado Flores, José",
      "Lourdes Varela",
      "RV1960",
      "Reina Valera",
      "Reina Valera 1909",
      "Reina Valera 1960",
      "Rick Warren",
      "Rodríguez Olaizola SJ, José María",
      "SAN JUAN DE LA CRUZ",
      "Verbo Divino",
      "Ynfante Jesus",
      "del Niño Jesús, Beato María Eugenio"
    ],
    "publishers": []
  },
  "literatura-ficcion": {
    "authors": [
      "Agatha Christie",
      "Ali Novak",
      "Bulgákov, Mijaíl",
      "CASSANDRA",
      "Calderone, Leandro",
      "Castro, Sofía",
      "Charli D Amelio",
      "Christie, Agatha",
      "Coetzee, J. M.",
      "DELGADO SANCHEZ, CRUZ",
      "Diego Fischer",
      "Douglas, Penelope",
      "Eloy Moreno",
      "GARCIA CALLEJA, CAMINO",
      "Han Kang",
      "J Maas, Sarah",
      "J.R.R. Tolkien",
      "JJ Benítez",
      "JULIO VERNE",
      "Jeff, Lindsay",
      "Jennifer Lynn Barnes",
      "Jenny Han",
      "Kass Morgan",
      "Kasten, Mona",
      "Laura G. Miranda",
      "Lendro Calderone",
      "Lisa Kleypas",
      "MIREZ, ALEX",
      "Ma José solano",
      "Marian Hale",
      "Mark Z Danielewski",
      "Marías, Javier",
      "Megan Maxwell",
      "Mircea Cartarescu",
      "Montero, Rosa",
      "R. F. Kuang",
      "Rivera, Ana Lena",
      "Rowling, J. K.",
      "Rómulo Gallegos",
      "SONIA FERNANDEZ-VIDAL",
      "Sarah J. Maas",
      "Sartre, Jean-Paul",
      "Sartre, Jean-Paul (1905-1980)",
      "Stephanie Meyer",
      "Suzanne Collins",
      "Tennessee Williams",
      "Tolkien, J. R. R.",
      "Wilde, Oscar",
      "Zahn, Timothy",
      "Stephen King",
      "King, Stephen",
      "Neil Gaiman",
      "Carlos Ruiz Zafón",
      "Ruiz Zafón, Carlos",
      "George R. R. Martin",
      "Martin, George R. R.",
      "Nora Roberts",
      "Roberts, Nora",
      "Paul Auster",
      "Orhan Pamuk",
      "Ayn Rand",
      "Anthony Doerr",
      "Doerr, Anthony",
      "Colleen Hoover",
      "Hoover, Colleen",
      "Julia Quinn",
      "Quinn, Julia",
      "Elísabet Benavent",
      "Alice Kellen",
      "Mercedes Ron",
      "Rebecca Yarros",
      "Holly Jackson",
      "Alice Oseman",
      "Oseman, Alice",
      "Florencia Bonelli",
      "Santiago Posteguillo",
      "Michael McDowell",
      "Ana Huang",
      "Leigh Bardugo",
      "Holly Black",
      "Black, Holly",
      "Maggie Stiefvater",
      "Stiefvater, Maggie",
      "Jennifer L. Armentrout",
      "Marissa Meyer",
      "Haruki Murakami",
      "Murakami, Haruki",
      "Émile Zola",
      "Zola, Émile",
      "Joe Abercrombie",
      "Abercrombie, Joe",
      "Roald Dahl",
      "Dahl, Roald"
    ],
    "publishers": []
  },
  "infantil-juvenil": {
    "authors": [
      "Andreae, Giles",
      "Andrés Marti",
      "BARNES, AYAX",
      "BLYTON ENID",
      "Baek, Heena",
      "Belen Lopez Medus y Maria Casabal",
      "CLARIN",
      "Cali, Davide",
      "Canticuénticos",
      "Czarny, Marcela",
      "Dani y Evan",
      "Disney",
      "Dr.Álvaro Bilbao",
      "Elma Van Vliet",
      "Enric Benito",
      "ErkenciShop",
      "Hillar, Ruth Maria",
      "INTELISANO G.",
      "Keiko Kasza",
      "LUCIA SERRANO",
      "Laura Borio",
      "Laura Vidal",
      "Lewis Gallart Y Otros",
      "Lopez Medus, Belen",
      "MORA, CAROLINA",
      "María Menéndez-Ponte",
      "McKee, David",
      "Melisa Jurozdicki",
      "Michael Morpurgo",
      "NAZARETH",
      "Oliver Jeffers",
      "PI KIDS",
      "Panicello Monterde, Victor",
      "Panini España",
      "Pernaudet, Christophe",
      "Porcelli Piussi, Liza",
      "Sam Falconer",
      "Santiago, Roberto",
      "Star Wars",
      "Yael Frankel",
      "Sam McBratney",
      "McBratney, Sam",
      "Eric Carle",
      "Carle, Eric",
      "Fiona Watt",
      "Watt, Fiona",
      "Megan Cullis",
      "Cullis, Megan",
      "Hervé Tullet",
      "Tullet, Hervé",
      "Manas, Pedro",
      "Pedro Mañas",
      "Orianne Lallemand",
      "Lallemand, Orianne",
      "Violeta Denou",
      "Scott Cawthon",
      "Cawthon, Scott",
      "Astley - Baker - Davies",
      "Nickelodeon",
      "Peppa Pig",
      "Navarro Blanco, Jesús",
      "NAVARRO BLANCO, JESÚS"
    ],
    "publishers": []
  },
  "psicologia": {
    "authors": [
      "AUTOR: R. GONZALEZ",
      "Aaron T. Beck y David A. Clark",
      "Alejandro Ariel",
      "Antonio Las Heras",
      "Azucena Borelle; Alicia de la Fe, Naida Kriznik",
      "Baños, Liliana",
      "Bromberg, Philip M.",
      "Calmels",
      "Colette Soler",
      "Cyrulnik, Boris",
      "Daniel Calmels",
      "Dolores Mosquera Barral",
      "Dylan Evans",
      "Eckell, Isabel",
      "Estela Shab, Daniel Kordon",
      "Francine Shapiro, Florence W. Kaslow y Louise Maxfield",
      "Franco Yago",
      "GAËTAN GATIAN DE CLÉRAMBAULT",
      "Gabriel Rolón",
      "Gary Emery y otros",
      "Henry Murray",
      "Ilda Levin",
      "John P. Dourley",
      "Jorge Eduardo Alonso",
      "Laura Stornini",
      "Lemoine Eugenie",
      "Mariela Bortolón",
      "Pepa Horno Goicoechea",
      "Rogers, Carl R.",
      "SHAPIRO, FORREST y otros",
      "Sergio Siciliano",
      "Sigmund, Freud",
      "YUNI JOSE A",
      "Carl Gustav Jung",
      "Jung, Carl Gustav",
      "Carl G. Jung",
      "Jung, Carl G.",
      "Carl Jung",
      "John Bowlby",
      "Bowlby, John",
      "Jacques-Alain Miller",
      "Miller, Jacques-Alain",
      "Luciano Lutereau",
      "Diana S. Rabinovich",
      "Esteban Levin",
      "Levin, Esteban",
      "Claudio Naranjo",
      "Laura Gutman",
      "Alicia Fernandez",
      "Rebeca Anijovich",
      "Anijovich, Rebeca",
      "Maritchu Seitún",
      "Bert Hellinger",
      "Peter A. Levine",
      "Levine, Peter A.",
      "Daniel Goleman",
      "Goleman, Daniel",
      "Margarita Maine",
      "MAINE, MARGARITA",
      "José Carlos Bermejo",
      "Bermejo, José Carlos",
      "Dutton, Kevin",
      "Kevin Dutton"
    ],
    "publishers": []
  },
  "naturaleza-animales": {
    "authors": [],
    "publishers": []
  },
  "deportes": {
    "authors": [],
    "publishers": []
  },
  "negocios-economia": {
    "authors": [
      "Benito, Cristina",
      "Chris Lowney",
      "Chris Voss",
      "Donald J Trump",
      "Ducos, Maria Marta",
      "Heath, Chip",
      "IASB",
      "John Maxwell",
      "Luis Pita, Luis Pita",
      "Matías Menéndez",
      "Milton Friedman con la colaboración de Rose D. Friedman",
      "Nassim Nicholas Taleb",
      "Nussbaumer Knaflic, Cole",
      "PRICE PRITCHETT",
      "Piñuel, Iñaki",
      "Serrano Ruiz, Francisca",
      "Verne Harnish",
      "Voss, Chris",
      "Benjamin Graham",
      "Graham, Benjamin",
      "Mary Buffett y David Clark",
      "Don Tapscott",
      "José Luis Espert",
      "Thomas Piketty",
      "Alex Hormozi"
    ],
    "publishers": []
  },
  "desarrollo-personal": {
    "authors": [
      "AMALIA ANDRADE ARANGO",
      "Anthony Robbins",
      "Bourbeau, Lise",
      "Brewer, Judson",
      "Buscaglia, Leo",
      "Champetier De Ribes, Brigitte",
      "DILTS, GILLIGAN",
      "Dispenza, Joe",
      "Dyer, Wayne W.",
      "Echegaray Inda, Guillermo",
      "Elisabeth Kübler-Ross",
      "Elizabeth Kübler-Ross",
      "Ferriss, Tim",
      "Franco Pisso",
      "Gary Chapman",
      "James Clear",
      "Jon Kabat-Zinn",
      "Juan Diego Gallego López",
      "Kabat-Zinn, Jon",
      "King, Patr",
      "LUIS LOPEZ GONZALEZ",
      "Lucy Leu",
      "MARGARITA SAHAGÚN",
      "Mario Alonso Puig, Mario Alonso Puig",
      "Marta Segrelles",
      "Martín Rieznik",
      "McDonald, Robert",
      "Meg Meeker",
      "Monty Roberts",
      "Napoleon Hill",
      "Navarro, Tomas",
      "Nele Meyer",
      "Raimon Samsó",
      "René J. Tossero",
      "Riso, Walter",
      "Rojas Estapé, Marián",
      "Rosenberg, Marshall B.",
      "Ryan Holiday",
      "SOSA RUBEN",
      "Samsó, Raimon",
      "Sharman Robin",
      "Victoria Conte",
      "Yoshinori Noguchi",
      "Jorge Bucay",
      "Allen Carr",
      "Russ Harris",
      "Jordan B. Peterson",
      "Bernardo Stamateas",
      "Stamateas, Bernardo",
      "Jane Nelsen",
      "Nelsen, Jane",
      "JANE NELSEN",
      "Dawn Huebner",
      "Huebner, Dawn",
      "Silvia Congost Provensal",
      "Congost Provensal, Silvia",
      "Míriam Tirado",
      "Tirado, Míriam",
      "Anamar Orihuela",
      "Orihuela, Anamar",
      "Louise Hay",
      "Hay, Louise",
      "Louise L. Hay",
      "NAWS"
    ],
    "publishers": []
  },
  "comics-manga": {
    "authors": [
      "Akira Toriyama",
      "Akutami, Gege",
      "Alan Moore, Frank Miller, Todd McFarlane",
      "Backderf, Derf",
      "CHARLIER - GIRAUD",
      "Charlie Adlard / Robert Kirkman",
      "Davis, Jim",
      "De Saint-Exupery, Antoine",
      "Flor M. Salvador",
      "GEGE AKUTAMI",
      "Gerry Duggan",
      "Hiromu Arakawa",
      "Joe, Hill",
      "Jonathan Hickman",
      "Kentaro Miura",
      "MARK RUSSELL - MIKE ALLRED.",
      "Quino",
      "Sankichi Hinodeya",
      "Toriyama, Akira",
      "Viplajo",
      "Yuhki Kamatani"
    ],
    "publishers": []
  },
  "idiomas-aprendizaje": {
    "authors": [
      "Border Rosemary",
      "Campbell Metcalf Y Otros",
      "Caron, Jean Luc/ Lebrun, Sandra",
      "Daphne Paizee",
      "Edwards, Lynda",
      "Falla, Tim",
      "GARCIA NEGRONI , MARIA MARTA",
      "Hastings, Bob",
      "Jones, Daniel",
      "Ladybird",
      "Latham-Koenig, Christina",
      "MURPHY, Raymond",
      "McCarthy, Michael",
      "NATIONAL GEOGRAPHIC LEARNING",
      "Nick KENNY",
      "Paul Korky / Thomas Valerie",
      "Read, Carol",
      "Sheila Dignen - Lynda Edwards",
      "Spencer, David",
      "Thompson, Tamzin",
      "Cambridge",
      "Editora Cambridge",
      "Richmond",
      "Macmillan",
      "Macmillan Education"
    ],
    "publishers": []
  },
  "filosofia-ciencias-sociales": {
    "authors": [
      "Alejandro Peña Esclusa",
      "Arendt, Hannah",
      "Bachelard, Gaston",
      "Butler, Judith",
      "Carballeda, Alfredo Juan Manuel",
      "Carla Delladonna, Rocío Uceda",
      "David Dorfman / Armand Mattelart",
      "Donald Robertson",
      "HOPPE HANS",
      "ITUARTE TELLAECHE, AMAYA",
      "JOHN KENNETH GALBRAITH",
      "Juan Miguel Zunzunegui",
      "León Tolstói",
      "Lev Tolstói",
      "Tolstói, Lev",
      "Sam Hamill",
      "Hamill Y Seaton",
      "Mariano Perez Carrasco",
      "Massimo Pigliucci y Gregory Lopez",
      "Nietzsche, Friedrich",
      "Pablo d Ors",
      "Ruocco, Juan",
      "Sayak Valencia",
      "Segato Rita Laura",
      "Stanley, Jason",
      "Byung Chul Han",
      "Byung-Chul Han",
      "Simone Weil",
      "Platón"
    ],
    "publishers": []
  },
  "medicina-salud": {
    "authors": [
      "A. I. Kapandji",
      "ALBA PADRO",
      "Alejandro Scicolone",
      "Alonso - Esquisabel",
      "Ana Maria Soprano",
      "Andrea Taddei",
      "Andreas Ludwig Kalcker",
      "Belaustegui, Isabel",
      "CATHERINE DOLTO",
      "CUETOS VEGA, Fernando",
      "Cabezuelo Gloria",
      "DRAKE, Richard",
      "Danièle Flaumenbaum",
      "Doctor Bayter",
      "Elizabeth Navarro",
      "García Merletti",
      "Glockler - Schurholz",
      "Gonzalez",
      "HAEBERLE, ERWIN",
      "Helen S. Kaplan",
      "Jesus Seco",
      "Joaquín Costa Subias & Juan Alfonso Soria Jerez",
      "LATTIN, DON",
      "Maggio Veronica",
      "Mara Liz Serra",
      "Mendoza Lara, Elvira",
      "Merce Marbes",
      "Michael Schuler",
      "Michel Odent",
      "Nayar, Ritu",
      "Noriega, Pablo",
      "Pablo Sanjurjo Crespo y ANTONIO BALDELLOU",
      "Roberto C. Frenquelli",
      "Rogers, Sally J",
      "SATI",
      "SEARS BARRY",
      "Torralva, Teresa",
      "Valls, Carme",
      "Henry Marsh",
      "Marsh, Henry",
      "Julio Basulto",
      "Basulto, Julio",
      "Anthony William",
      "William, Anthony",
      "Carlos Jaramillo",
      "Jaramillo, Carlos",
      "Jesús Martín-Fernández",
      "JESUS MARTIN FERNANDEZ",
      "Mary Gaskin"
    ],
    "publishers": []
  },
  "ciencia-tecnologia": {
    "authors": [
      "AUDESIRK, TERESA",
      "BOARD, Jon & CROSS, Alan",
      "Bruice, Paula Yurkanis",
      "Derek B. Lowe",
      "Dr. Chris Colles",
      "FONT ROVIRA, FRANCESC",
      "Federico Kukso",
      "García Bocanegra. Ignacio",
      "Grinberg-Zylberbaum, Jacobo",
      "Gustavo Eduardo D'Elia",
      "Jose Colera Jimenez",
      "LOPESINO CORRAL, JORDI",
      "MATTHES, ERIC",
      "Margulis, Lynn",
      "ROBERT SAPOLSKY",
      "Raymond Chang - Jason Overby",
      "Martin, Robert C.",
      "Robert C. Martin",
      "Raúl Rivas",
      "Ron Larson",
      "SANZ TIMON, JOSE MANUEL",
      "Sears / Zemansky / Young / Freedman",
      "URRESTARAZU GAVILAN, MIGUELá"
    ],
    "publishers": []
  },
  "historia": {
    "authors": [
      "Alejandro Dumas",
      "Ana Maria Cabrera",
      "Dominique Lapierre / Larry Collins",
      "EDMUNDO WERNICKE",
      "Francis Bond Head",
      "GILLES PERRAULT",
      "Gloria Delgado",
      "Gordon Thomas",
      "Guilhem Olivier",
      "Ian Kershaw",
      "Ilan Pappe",
      "Jose M. Gutierrez De La Camara Señan",
      "Kraus, Otto B.",
      "LAPIERRE, DOMINIQUE",
      "Michael H. Kater",
      "Raymond Cartier",
      "SABORIDO JORGE",
      "René Favaloro",
      "Ceferino Reato",
      "Juan B. Yofre",
      "Massimiliano Afiero",
      "Afiero, Massimiliano"
    ],
    "publishers": []
  },
  "derecho": {
    "authors": [
      "Jakobs, Günther",
      "Manzanero, Antonio Lucas"
    ],
    "publishers": []
  },
  "cocina-gastronomia": {
    "authors": [
      "Aleja Díaz",
      "Betular, Damian",
      "Luisina Troncoso",
      "Phaidon Editors",
      "Roca Paulina"
    ],
    "publishers": []
  }
};

// ─── Palabras/frases distintivas por categoría (independientes de autor) ───
// Regla: nunca una sola palabra genérica corta decide sola — cada entrada acá
// es una frase de 2+ palabras, o una palabra suficientemente específica
// (ej. "tarot", "biblia", "manga") que casi no aparece fuera de su rubro.
// Se buscan como substring dentro del título normalizado (sin acentos, en
// minúscula). Cada entrada puede fijar subcategoryId — si no, queda sin
// subcategoría (null). Confianza más baja que un autor reconocido (ver
// classify.js). CF-CATEGORÍAS-2C: ampliado a partir del análisis de
// frecuencia de palabras sobre los 4.437 activos que habían quedado sin
// categoría específica en la V1 (ver scripts/categorize/data/word_freq —
// no versionado, generado ad-hoc para este lote).
function kw(phrase, subcategoryId = null, allowSecondary = false) {
  return { phrase, subcategoryId, allowSecondary };
}

export const KEYWORD_SIGNALS = {
  'esoterismo-tarot': [
    kw('tarot', 'tarot-oraculos'), kw('oraculo', 'tarot-oraculos'),
    kw('oraculos', 'tarot-oraculos'), kw('cartas oraculo', 'tarot-oraculos'),
    kw('runas', 'tarot-oraculos'), kw('wicca'), kw('brujeria'),
    kw('chamanismo'),
    kw('astrologia kabbalistica', 'cabala-kabbalah'),
    kw('kabbalah', 'cabala-kabbalah'), kw('kabbalistica', 'cabala-kabbalah'),
    kw('cabala mistica', 'cabala-kabbalah'), kw('cabala', 'cabala-kabbalah'),
    kw('kabala', 'cabala-kabbalah'),
    kw('sabiduria de los idiotas', 'sufismo'),
    kw('merkaba', 'cabala-kabbalah'),
    kw('sefer atzilut', 'cabala-kabbalah'),
    kw('astrologia', 'astrologia'), kw('horoscopo', 'astrologia'), kw('grimorio'),
    kw('hechiceria'), kw('numerologia'), kw('quiromancia'), kw('yoga'),
    kw('meditacion'), kw('magia'), kw('reiki'),
    kw('angeles'), kw('alma'),
  ],
  'religion-espiritualidad': [
    // Obras SOBRE la Biblia no son una edición bíblica. Estas señales
    // específicas deben evaluarse antes que la palabra genérica "biblia".
    // QA BIBLES-RVR-GROWTH-1: 20 publicaciones activas (12 ediciones tras
    // dedupe) contaminaban la landing comercial de Biblias.
    kw('evangelio de los esenios', 'espiritualidad'),
    kw('como estudiar e interpretar la biblia', 'espiritualidad'),
    kw('comprender las escrituras', 'espiritualidad'),
    kw('atlas didactico de la biblia', 'espiritualidad'),
    kw('mapas atlas didactico de la biblia', 'espiritualidad'),
    kw('nuevos enigmas de la biblia', 'espiritualidad'),
    kw('enigmas de la biblia', 'espiritualidad'),
    kw('enigmas biblia', 'espiritualidad'),
    kw('biblia libro por libro', 'espiritualidad'),
    kw('buena noticia de cada dia', 'espiritualidad'),
    kw('lucas evangelista', 'espiritualidad'),
    kw('jesus maestro', 'espiritualidad'),
    kw('biblia coran tanaj', 'otras-tradiciones'),
    kw('reina valera', 'reina-valera'), kw('rvr1960', 'reina-valera'),
    kw('rvr 1960', 'reina-valera'), kw('rv1960', 'reina-valera'),
    kw('rv 1960', 'reina-valera'), kw('biblia', 'biblia'),
    kw('nuevo testamento', 'biblia'), kw('antiguo testamento', 'biblia'),
    kw('catecismo', 'espiritualidad'), kw('teologia', 'espiritualidad'),
    kw('iglesia catolica', 'espiritualidad'),
    kw('espiritualidad cristiana', 'espiritualidad'),
    kw('sagrada escritura', 'biblia'), kw('salmos', 'espiritualidad'),
    kw('jesus de nazaret', 'espiritualidad'),
    kw('vida de jesus', 'espiritualidad'),
    kw('mundo de jesus', 'espiritualidad'),
    kw('fe cristiana', 'espiritualidad'),
    kw('vida cristiana', 'espiritualidad'),
    kw('cristianismo', 'espiritualidad'),
    kw('buscadores de dios', 'espiritualidad'),
    kw('obedecere a dios', 'espiritualidad'),
    kw('conforme al corazon de dios', 'espiritualidad'),
    kw('dios tiene un proposito contigo', 'espiritualidad'),
    kw('jesus always', 'espiritualidad'),
    kw('hablemos de dios', 'espiritualidad'),
    kw('mundo jesus', 'espiritualidad'),
    kw('guia de lectura jesus', 'espiritualidad'),
    kw('sabiduria judia', 'espiritualidad'),
    kw('jesus esta vivo', 'espiritualidad'),
    kw('papa leon xiv', 'espiritualidad'),
    kw('santo rosario', 'espiritualidad'),
    kw('hijos amados de dios', 'espiritualidad'),
    kw('dios habla con arjuna', 'espiritualidad'),
  ],
  'infantil-juvenil': [
    kw('cuento infantil', 'literatura-infantil'),
    kw('cuentos infantiles', 'literatura-infantil'),
    kw('para ninos', 'literatura-infantil'),
    kw('libro infantil', 'literatura-infantil'),
    kw('colorear', 'actividades-aprendizaje'),
    kw('para colorear', 'actividades-aprendizaje'),
    kw('primera infancia', 'primera-infancia'),
    kw('juvenil', 'literatura-juvenil'), kw('young adult', 'literatura-juvenil'),
    kw('cuento', 'literatura-infantil'), kw('cuentos', 'literatura-infantil'),
    kw('bebe', 'primera-infancia'), kw('ninos', 'literatura-infantil'),
    kw('nino', 'literatura-infantil'), kw('disney', 'literatura-infantil'),
    kw('marvel', 'literatura-infantil'), kw('actividades', 'actividades-aprendizaje'),
    kw('adolescentes', 'literatura-juvenil'),
  ],
  'comics-manga': [
    kw('god of war'), kw('manga'), kw('comic'), kw('cómic'), kw('novela grafica'),
    kw('novela gráfica'), kw('historieta'),
  ],
  'cocina-gastronomia': [
    kw('receta'), kw('recetas'), kw('cocina'), kw('gastronomia'),
    kw('gastronomía'), kw('reposteria'), kw('pasteleria'), kw('culinari'),
  ],
  'idiomas-aprendizaje': [
    kw('workbook', 'ingles'), kw("student's book", 'ingles'),
    kw('grammar in use', 'ingles'), kw('phrasal verbs', 'ingles'),
    kw('english file', 'ingles'), kw('aprender ingles', 'ingles'),
    kw('diccionario ingles', 'ingles'), kw('cambridge english', 'ingles'),
    kw('gramatica inglesa', 'ingles'), kw('diccionario'), kw('english', 'ingles'),
    kw('oxford', 'ingles'), kw('with cd', 'ingles'),
    kw("pupil's book", 'ingles'), kw('pupils book', 'ingles'),
    kw('activity book', 'ingles'), kw('kids box', 'ingles'),
    kw('super minds', 'ingles'), kw('work book', 'ingles'),
    kw('lenguaje'), kw('ingles', 'ingles'),
  ],
  'psicologia': [
    kw('psicoanalisis', 'psicoanalisis', true), kw('psicoanálisis', 'psicoanalisis', true),
    kw('practica psicomotriz', 'psicomotricidad', true),
    kw('tratamiento psiquico', 'psicologia-clinica'),
    kw('psicomotricidad', 'psicomotricidad', true),
    kw('psicoterapia', 'psicoterapia', true),
    kw('terapia cognitiva', 'psicoterapia', true),
    kw('terapia sistemica', 'psicoterapia', true),
    kw('psicologia clinica', 'psicologia-clinica'),
    kw('trastorno de ansiedad', 'psicologia-clinica'),
    kw('trastorno del espectro autista', 'autismo-neurodesarrollo', true),
    kw('espectro autista', 'autismo-neurodesarrollo', true),
    kw('autismo', 'autismo-neurodesarrollo', true),
    kw('psicologia del desarrollo', 'neuropsicologia'),
    kw('psicologia', 'psicologia-clinica'), kw('lacan', 'psicoanalisis'),
    kw('freud', 'psicoanalisis'), kw('carl jung', 'psicoanalisis'),
  ],
  'naturaleza-animales': [
    kw('zoologia', 'zoologia-animales'),
    kw('zoologicas', 'zoologia-animales'),
    kw('equitacion', 'caballos-equitacion'),
    kw('ecuestre', 'caballos-equitacion'),
    kw('cerebro equino', 'caballos-equitacion'),
    kw('anatomia del caballo', 'caballos-equitacion'),
    kw('caballo deportivo', 'caballos-equitacion'),
    kw('salud del caballo', 'caballos-equitacion'),
    kw('obstetricia equina', 'caballos-equitacion'),
  ],
  'deportes': [
    kw('messi por amor a la camiseta', 'futbol'),
    kw('futbol', 'futbol'), kw('fútbol', 'futbol'),
    kw('rugby', 'otros-deportes'), kw('tenis', 'otros-deportes'),
    kw('ajedrez', 'otros-deportes'), kw('deporte', 'otros-deportes'),
    kw('deportivo', 'otros-deportes'),
  ],
  'medicina-salud': [
    kw('medicina interna'), kw('anatomia', 'anatomia'),
    kw('anatomía', 'anatomia'), kw('fisiologia'), kw('fisiología'),
    kw('farmacologia'), kw('farmacología'), kw('clinica medica'),
    kw('manual clinico'), kw('enfermeria', 'enfermeria'),
    kw('nutricion clinica', 'nutricion'), kw('pediatria'), kw('cardiologia'),
    kw('psoriasis', 'dermatologia', true), kw('dermatitis', 'dermatologia', true),
    kw('eczema', 'dermatologia', true), kw('acne', 'dermatologia', true),
    kw('trastorno', 'salud-mental'), kw('trastornos', 'salud-mental'),
    kw('parteria'),
    kw('ansiedad', 'salud-mental'), kw('tdah', 'salud-mental'),
    kw('depresion', 'salud-mental'), kw('depresión', 'salud-mental'),
    kw('abuso sexual', 'salud-mental'), kw('atlas', 'anatomia'),
    kw('nutricion', 'nutricion'), kw('salud'), kw('cuerpo'), kw('cerebro'),
    kw('mente', 'salud-mental'), kw('medicina'), kw('clinica'),
    kw('enfermedades'), kw('tratamiento'), kw('diagnostico'),
  ],
  'derecho': [
    kw('derecho penal'), kw('derecho civil'), kw('codigo civil'),
    kw('código civil'), kw('derecho procesal'), kw('jurisprudencia'),
  ],
  'negocios-economia': [
    kw('marketing'), kw('finanzas personales'), kw('emprendimiento'),
    kw('negociacion'), kw('liderazgo empresarial'), kw('management'),
    kw('estrategia de negocios'), kw('economia'), kw('gestion'),
    kw('liderazgo'),
  ],
  'ciencia-tecnologia': [
    kw('clean code', 'informatica-software', true),
    kw('codigo limpio', 'informatica-software', true),
    kw('desarrollo de software', 'informatica-software', true),
    kw('ingenieria de software', 'informatica-software', true),
    kw('software', 'informatica-software', true),
    kw('programacion', 'programacion'), kw('programación', 'programacion'),
    kw('quimica organica', 'fisica-quimica'),
    kw('quimica general', 'fisica-quimica'),
    kw('fisica universitaria', 'fisica-quimica'),
    kw('biologia molecular', 'biologia'),
    kw('matematica universitaria', 'matematica'),
    kw('calculo diferencial', 'matematica'),
    kw('matematica', 'matematica'), kw('matemática', 'matematica'),
    kw('ciencia'), kw('ciencias'),
  ],
  'historia': [
    kw('segunda guerra mundial', 'historia-mundial'),
    kw('primera guerra mundial', 'historia-mundial'),
    kw('historia de uruguay', 'historia-argentina-uruguay'),
    kw('historia argentina', 'historia-argentina-uruguay'),
    kw('revolucion rusa', 'historia-mundial'),
    kw('historia contemporanea', 'historia-mundial'),
    kw('memorias'), kw('biografia'), kw('biografía'), kw('historia'),
    kw('guerra', 'historia-mundial'),
  ],
  'arte-diseno-fotografia': [
    kw('diseño grafico'), kw('diseno grafico'), kw('fotografia'),
    kw('historia del arte'), kw('ilustracion'), kw('ilustración'),
    kw('arte'),
  ],
  'filosofia-ciencias-sociales': [
    kw('filosofia', 'filosofia'), kw('filosofía', 'filosofia'),
    kw('taoismo', 'filosofia'), kw('chuang tse', 'filosofia'),
    kw('sociologia', 'sociologia-antropologia'),
    kw('antropologia', 'sociologia-antropologia'),
    kw('ciencia politica', 'ciencia-politica', true),
    kw('emociones politicas', 'ciencia-politica', true),
    kw('emocion politica', 'ciencia-politica', true),
    kw('teoria critica', 'sociologia-antropologia'), kw('ensayo'),
  ],
  'familia-crianza': [
    kw('maternidad', 'maternidad', true), kw('embarazo', 'maternidad', true),
    kw('posparto', 'maternidad', true), kw('postparto', 'maternidad', true),
    kw('lactancia', 'maternidad', true), kw('crianza', 'crianza', true),
  ],
  'educacion': [
    kw('pedagogia', 'pedagogia'), kw('pedagogía', 'pedagogia'),
    kw('didactica', 'pedagogia'), kw('nivel inicial', 'pedagogia'),
    kw('formacion docente', 'formacion-docente'), kw('montessori', 'pedagogia'),
    kw('educacion', 'pedagogia'), kw('escuela', 'formacion-docente'),
    kw('aprendizaje', 'pedagogia'), kw('aprender'),
  ],
  'literatura-ficcion': [
    kw('novela', 'novela'), kw('teatro', 'teatro'), kw('poesia', 'poesia'),
    kw('poesía', 'poesia'), kw('policial', 'policial-suspenso'),
    kw('suspenso', 'policial-suspenso'), kw('misterio', 'policial-suspenso'),
    kw('ciencia ficcion', 'ciencia-ficcion-fantasia'),
    kw('ciencia ficción', 'ciencia-ficcion-fantasia'),
    kw('fantasia', 'ciencia-ficcion-fantasia'),
    kw('fantasía', 'ciencia-ficcion-fantasia'),
    kw('cuentos completos', 'cuento'), kw('relatos', 'cuento'),
    kw('secreto'), kw('literatura'),
  ],
  'desarrollo-personal': [
    kw('duelo'), kw('mindfulness'), kw('miedo'), kw('habitos'),
    kw('autoayuda'), kw('motivacion'),
  ],
};

// Segunda pasada, solo si nada de lo anterior matcheó: palabras sueltas
// bastante genéricas que igual dan una señal razonable — confianza más baja
// (ver CONFIDENCE.KEYWORD_WEAK en classify.js). Ninguna decide sola contra
// una coincidencia de autor/editorial/frase fuerte.
export const KEYWORD_SIGNALS_WEAK = {
  'infantil-juvenil': [kw('juego'), kw('juegos'), kw('album')],
  // 'mundo'/'vida' se retiraron (CF-CATEGORÍAS-2D, hallado en QA): eran
  // demasiado genéricas — mandaban decenas de libros de autoayuda/negocios/
  // crianza a "historia" solo por contener esas palabras sueltas.
  'desarrollo-personal': [kw('poder'), kw('mejor'), kw('vivir')],
  // Sellos/colecciones de bolsillo dedicados casi exclusivamente a ficción
  // literaria (visto en el análisis de otros-libros: Paul Auster, Nora
  // Roberts, Orhan Pamuk, George R. R. Martin bajo estos sellos) — señal
  // débil porque el sello no garantiza género, solo lo hace muy probable.
  'literatura-ficcion': [kw('booket', 'novela'), kw('debolsillo', 'novela')],
};

// ─── Señales de tipo "no es un libro" con sub-tipo ─────────────────────────
// A diferencia de OBJECT_SIGNALS (abajo), estas señales fijan también el
// `type` (music/magazine/object) y la subcategoría dentro de
// "otros-productos" — CF-CATEGORÍAS-2C: estos productos quedan VISIBLES en
// el catálogo bajo esa categoría comercial, no ocultos.
export const OBJECT_TYPE_SIGNALS = [
  // Música — 'vinilo'/'cd'/'lp'/'dvd' se resuelven aparte como palabra
  // exacta en classify.js (ver findObjectSignal), no acá.
  { phrase: 'lp remasterizado', type: 'music', subcategoryId: 'discos-vinilos' },
  { phrase: 'disco cd', type: 'music', subcategoryId: 'discos-vinilos' },
  { phrase: 'cd fisico', type: 'music', subcategoryId: 'discos-vinilos' },
  { phrase: 'edicion cd', type: 'music', subcategoryId: 'discos-vinilos' },
  { phrase: 'cd para coleccion', type: 'music', subcategoryId: 'discos-vinilos' },
  { phrase: 'vinilo', type: 'music', subcategoryId: 'discos-vinilos' },
  // Revistas / efímera periódica
  { phrase: 'lote de revistas', type: 'magazine', subcategoryId: 'revistas' },
  { phrase: 'revista coleccionista', type: 'magazine', subcategoryId: 'revistas' },
  { phrase: 'fasciculo coleccionable', type: 'magazine', subcategoryId: 'revistas' },
  { phrase: 'revista', type: 'magazine', subcategoryId: 'revistas' },
  // Manualidades / papelería / merchandising
  { phrase: 'cartuchera', type: 'object', subcategoryId: 'papeleria-manualidades' },
  { phrase: 'estuche de cosmeticos', type: 'object', subcategoryId: 'papeleria-manualidades' },
  { phrase: 'estuche de maquillaje', type: 'object', subcategoryId: 'papeleria-manualidades' },
  { phrase: 'vincha tiara', type: 'object', subcategoryId: 'papeleria-manualidades' },
  { phrase: 'kit de ganchillo', type: 'object', subcategoryId: 'papeleria-manualidades' },
  { phrase: 'kit de crochet', type: 'object', subcategoryId: 'papeleria-manualidades' },
  { phrase: 'crochet', type: 'object', subcategoryId: 'papeleria-manualidades' },
  { phrase: 'amigurumi', type: 'object', subcategoryId: 'papeleria-manualidades' },
  { phrase: 'flashcards', type: 'object', subcategoryId: 'papeleria-manualidades' },
  { phrase: 'agenda 20', type: 'object', subcategoryId: 'papeleria-manualidades' },
  { phrase: 'planner', type: 'object', subcategoryId: 'papeleria-manualidades' },
  { phrase: 'adhesivos', type: 'object', subcategoryId: 'papeleria-manualidades' },
  { phrase: 'expansion juego de mesa', type: 'object', subcategoryId: 'papeleria-manualidades' },
  { phrase: 'juego de mesa', type: 'object', subcategoryId: 'papeleria-manualidades' },
];

// ─── Señales de "no es un libro" (objetos de colección/antigüedades) ──────
// Ampliado desde la lista original de BestsellerSection.astro (24 términos,
// probado insuficiente en CF-CATEGORÍAS-IA-DIAGNÓSTICO: solo detectaba 5 de
// 200 objetos reales) con lo aprendido clasificando a mano ~600 casos reales
// en CF-CATEGORÍAS-0B/0C. subcategoryId fijo: 'objetos-coleccion'.
export const OBJECT_SIGNALS = [
  'cruz', 'crucifijo', 'bronce', 'chapa esmaltada', 'cartel chapa', 'dije',
  'plata 925', 'jaspe', 'colgante vintage', 'sacapuntas vintage',
  'candelabro', 'figura bronce', 'figuras bronce', 'decorativo', 'decorativa',
  'pared cristo', 'cristo inri', 'inri antigua', 'jeringa',
  'veterinaria vidrio', 'volante cine', 'antiguo matrimonio',
  'antigua veterinaria', 'pieza antigua', 'objeto antiguo', 'medalla',
  'moneda antigua', 'estampilla', 'sello postal', 'reloj antiguo',
  'llavero antiguo', 'gemelos antiguo', 'insignia', 'uniforme antiguo',
  'espada', 'daga', 'miniatura decorativo', 'maquina de escribir',
  'radio antigua', 'camara fotografica antigua', 'automobilia',
  'matricula vintage', 'matricula antigua', 'postales antiguas',
  'plato limoges', 'porcelana', 'ceramica antigua', 'pesas antiguas',
  'prendedor plata', 'anillo plata 925',
];

// Umbral de fan-out para considerar un rasgo "genérico" en vez de específico
// de una categoría — usado por classify.js al validar coincidencias débiles.
export const MIN_KEYWORD_LENGTH = 4;
