// scripts/categorize/rules.js
//
// Reglas determinísticas para CF-CATEGORÍAS-1 — separadas de la ejecución
// (classify.js las consume, run.js decide cuándo reclasificar). Versionar
// RULES_VERSION cada vez que se cambien listas de autores/keywords/objetos:
// run.js usa esta versión (junto con TAXONOMY_VERSION) para decidir si un
// registro ya clasificado necesita reclasificarse.
//
// Origen de los datos: MINED_AUTHOR_SIGNALS se extrajo programáticamente de
// los ~600 casos clasificados a mano en las sesiones CF-CATEGORÍAS-0B y 0C
// (autor real -> categoría real, revisado uno por uno, no adivinado). Los
// autores genéricos ("VV. AA.", "Varios autores", "Sin Autor", etc., que
// aparecían repetidos en categorías distintas) se filtraron antes de esta
// exportación porque no son una señal útil.

export const RULES_VERSION = 3;

export const MINED_AUTHOR_SIGNALS = {
  "esoterismo-tarot": {
    "authors": [
      "AIGUA DE VALENCIA",
      "ALANA FAIRCHILD ; ISABEL BRYNA",
      "ANNE STOKES",
      "Aldo Lavagnini",
      "Alice Bailey",
      "Astromostra",
      "Benitez, J. J.",
      "Blake, Deborah",
      "Bulard-Cordeau, Brigitte",
      "CONNY MENDEZ",
      "Café, Sônia",
      "Ciro Marchetti",
      "DARCEY, CHERALYN",
      "Dass, Ram",
      "Doreen Virtue",
      "EDUARDO MADIROLAS",
      "FOURNIER",
      "Gabriel Silva",
      "Graciela Iriondo",
      "H.P. Blavatsky",
      "Hawkins, David",
      "IÑIGUEZ PUEBLA, AFRICA",
      "J. A. Portela",
      "J.J. Benítez",
      "JOHN MATTEWS",
      "LO SCARABEO",
      "LUCY CAVENDISH",
      "Leaping Hare",
      "Lisa Parker",
      "MARCHETTI , FRANCISCO A. ³ ESCUELA DE CABALA DE MARIO SABAN",
      "Mabel Collins",
      "Monika Correia Nobre",
      "Omar Hejeile",
      "ROBERTO DE ANGELIS",
      "STOPFORTH, BUTLER",
      "SWAMI SRI YUKTESWAR",
      "Salerno Toni Carmine",
      "Travis McHenry",
      "Vanesa Maiorana",
      "Yoshi Yoshitani"
    ],
    "publishers": [
      "Da Brigh",
      "LENORMAND",
      "Lo Scarabeo",
      "Oberon",
      "Rockpool Publishing",
      "Tarot"
    ]
  },
  "arte-diseno-fotografia": {
    "authors": [
      "3dtotal Publishing",
      "Akira D Tobirama",
      "Byrne, David",
      "Caldas, Sara",
      "Cruz Delgado Sánchez",
      "Czerny, Carl",
      "DAVID ABDREU BACH",
      "DENNIC CHUNMAN LO",
      "ENRIC JARDI",
      "Harry, Debbie",
      "JAMES BASTIEN",
      "JAN SWAFFORD",
      "MOY SANTANA, ANTONIO JOSE ALBERTOS",
      "Mario Pons Sansegundo",
      "Oasis",
      "Smith, Keri",
      "Violeta Hemsy de Gainza"
    ],
    "publishers": []
  },
  "educacion": {
    "authors": [
      "Alicia Oiberman",
      "Anya Damiron y Pablo Pino",
      "BEATRIZ ACTIS (Comp.)",
      "Brailovsky, Daniel",
      "Cañeque, Hilda",
      "DOLORS OLIVER AGÜERA",
      "Duvouldy, Marine",
      "Faber, Adele",
      "Grunfeld, Diana",
      "Grunin, Julián",
      "Harf, Ruth",
      "Howard Gardner",
      "JOSÉ MARTÍNEZ ROMERO",
      "Klara Moncho",
      "Laura Pitluk",
      "Liliana Gruss / Francis Rosemberg",
      "MON ESPINOSA",
      "Malajovich, Ana",
      "Mariana Morales y Juan Fernandez",
      "Miller, Alice",
      "Monica Coronado",
      "PAOLA DOGLIOTTI MORO",
      "Priscilla Vela, Mercedes Herran, Priscilla Vela, Mercedes Herran",
      "Pujato, Beatriz",
      "Romero, Claudia Compiladora",
      "SKINNER, Gary & OTHERS",
      "Stanislas Dehaene",
      "TERRITORIOS DE JUEGO Y EXPLORACION",
      "Valeria Abusamra",
      "Wagnon, Sylvain"
    ],
    "publishers": [
      "Neuroaprendizaje"
    ]
  },
  "religion-espiritualidad": {
    "authors": [
      "American Bible Society",
      "Anthony De Mello",
      "Ariel Álvarez Valdes",
      "Aryeh Kaplan",
      "B&H Español",
      "Bernard Hurault",
      "Celam",
      "Cyrulnik, Boris",
      "David Wilkerson",
      "Descleé de Brouwer",
      "Ediciones san Pablo",
      "Editorial Vida",
      "Elena G. de White",
      "FRANZ JALICS",
      "Francesco Castelli",
      "Francisco Cantera Burgos;Manuel Iglesias González",
      "Instituto Fe y Vida",
      "John MacArthur",
      "Lecturas Dr. George Guthrie",
      "MADRE TERESA DE CALCUTA, NúRIA PUJOL VALLS, MADRE TERESA DE CALCUTA, NúRIA PUJOL VALLS",
      "Mazzoni, Lorenzo",
      "NAWS",
      "Núñez, Miguel",
      "RV1960",
      "Rav Berg",
      "Reina Valera",
      "Reina Valera 1909",
      "Reina Valera 1960",
      "Rick Warren",
      "Rodríguez Olaizola SJ, José María",
      "SAN JUAN DE LA CRUZ",
      "Verbo Divino",
      "Ynfante Jesus",
      "del Niño Jesús, Beato María Eugenio"
    ],
    "publishers": []
  },
  "literatura-ficcion": {
    "authors": [
      "Agatha Christie",
      "Ali Novak",
      "Bulgákov, Mijaíl",
      "CASSANDRA",
      "Calderone, Leandro",
      "Castro, Sofía",
      "Charli D Amelio",
      "Christie, Agatha",
      "Coetzee, J. M.",
      "DELGADO SANCHEZ, CRUZ",
      "Diego Fischer",
      "Douglas, Penelope",
      "Eloy Moreno",
      "GARCIA CALLEJA, CAMINO",
      "Han Kang",
      "J Maas, Sarah",
      "J.R.R. Tolkien",
      "JJ Benítez",
      "JULIO VERNE",
      "Jeff, Lindsay",
      "Jennifer Lynn Barnes",
      "Jenny Han",
      "Kass Morgan",
      "Kasten, Mona",
      "Laura G. Miranda",
      "Lendro Calderone",
      "Lisa Kleypas",
      "MIREZ, ALEX",
      "Ma José solano",
      "Marian Hale",
      "Mark Z Danielewski",
      "Marías, Javier",
      "Megan Maxwell",
      "Mircea Cartarescu",
      "Montero, Rosa",
      "R. F. Kuang",
      "Rivera, Ana Lena",
      "Rowling, J. K.",
      "Rómulo Gallegos",
      "SONIA FERNANDEZ-VIDAL",
      "Sarah J. Maas",
      "Sartre, Jean-Paul",
      "Sartre, Jean-Paul (1905-1980)",
      "Stephanie Meyer",
      "Suzanne Collins",
      "Tennessee Williams",
      "Tolkien, J. R. R.",
      "Wilde, Oscar",
      "Zahn, Timothy"
    ],
    "publishers": []
  },
  "infantil-juvenil": {
    "authors": [
      "Andreae, Giles",
      "Andrés Marti",
      "BARNES, AYAX",
      "BLYTON ENID",
      "Baek, Heena",
      "Belen Lopez Medus y Maria Casabal",
      "CLARIN",
      "Cali, Davide",
      "Canticuénticos",
      "Czarny, Marcela",
      "Dani y Evan",
      "Disney",
      "Dr.Álvaro Bilbao",
      "Elma Van Vliet",
      "Enric Benito",
      "ErkenciShop",
      "Hillar, Ruth Maria",
      "INTELISANO G.",
      "Keiko Kasza",
      "LUCIA SERRANO",
      "Laura Borio",
      "Laura Vidal",
      "Lewis Gallart Y Otros",
      "Lopez Medus, Belen",
      "MORA, CAROLINA",
      "María Menéndez-Ponte",
      "McKee, David",
      "Melisa Jurozdicki",
      "Michael Morpurgo",
      "NAZARETH",
      "Oliver Jeffers",
      "PI KIDS",
      "Panicello Monterde, Victor",
      "Panini España",
      "Pernaudet, Christophe",
      "Porcelli Piussi, Liza",
      "Sam Falconer",
      "Santiago, Roberto",
      "Star Wars",
      "Yael Frankel"
    ],
    "publishers": []
  },
  "psicologia": {
    "authors": [
      "AUTOR: R. GONZALEZ",
      "Aaron T. Beck y David A. Clark",
      "Alejandro Ariel",
      "Antonio Las Heras",
      "Azucena Borelle; Alicia de la Fe, Naida Kriznik",
      "Baños, Liliana",
      "Bromberg, Philip M.",
      "Calmels",
      "Colette Soler",
      "Cyrulnik, Boris",
      "Daniel Calmels",
      "Dolores Mosquera Barral",
      "Dylan Evans",
      "Eckell, Isabel",
      "Estela Shab, Daniel Kordon",
      "Francine Shapiro, Florence W. Kaslow y Louise Maxfield",
      "Franco Yago",
      "GAËTAN GATIAN DE CLÉRAMBAULT",
      "Gabriel Rolón",
      "Gary Emery y otros",
      "Henry Murray",
      "Ilda Levin",
      "John P. Dourley",
      "Jorge Eduardo Alonso",
      "Laura Stornini",
      "Lemoine Eugenie",
      "Mariela Bortolón",
      "Martin, Robert C.",
      "Pepa Horno Goicoechea",
      "Rogers, Carl R.",
      "SHAPIRO, FORREST y otros",
      "Sergio Siciliano",
      "Sigmund, Freud",
      "YUNI JOSE A"
    ],
    "publishers": []
  },
  "negocios-economia": {
    "authors": [
      "Benito, Cristina",
      "Chris Lowney",
      "Chris Voss",
      "Donald J Trump",
      "Ducos, Maria Marta",
      "Heath, Chip",
      "IASB",
      "John Maxwell",
      "Luis Pita, Luis Pita",
      "Matías Menéndez",
      "Milton Friedman con la colaboración de Rose D. Friedman",
      "Nassim Nicholas Taleb",
      "Nussbaumer Knaflic, Cole",
      "PRICE PRITCHETT",
      "Piñuel, Iñaki",
      "Serrano Ruiz, Francisca",
      "Verne Harnish",
      "Voss, Chris"
    ],
    "publishers": []
  },
  "desarrollo-personal": {
    "authors": [
      "AMALIA ANDRADE ARANGO",
      "Anthony Robbins",
      "Bourbeau, Lise",
      "Brewer, Judson",
      "Buscaglia, Leo",
      "Champetier De Ribes, Brigitte",
      "DILTS, GILLIGAN",
      "Dispenza, Joe",
      "Dyer, Wayne W.",
      "Echegaray Inda, Guillermo",
      "Elisabeth Kübler-Ross",
      "Elizabeth Kübler-Ross",
      "Ferriss, Tim",
      "Franco Pisso",
      "Gary Chapman",
      "James Clear",
      "Jon Kabat-Zinn",
      "Juan Diego Gallego López",
      "Kabat-Zinn, Jon",
      "King, Patr",
      "LUIS LOPEZ GONZALEZ",
      "Lucy Leu",
      "MARGARITA SAHAGÚN",
      "Mario Alonso Puig, Mario Alonso Puig",
      "Marta Segrelles",
      "Martín Rieznik",
      "McDonald, Robert",
      "Meg Meeker",
      "Monty Roberts",
      "Napoleon Hill",
      "Navarro, Tomas",
      "Nele Meyer",
      "Raimon Samsó",
      "René J. Tossero",
      "Riso, Walter",
      "Rojas Estapé, Marián",
      "Rosenberg, Marshall B.",
      "Ryan Holiday",
      "SOSA RUBEN",
      "Samsó, Raimon",
      "Sharman Robin",
      "Victoria Conte",
      "Yoshinori Noguchi"
    ],
    "publishers": []
  },
  "comics-manga": {
    "authors": [
      "Akira Toriyama",
      "Akutami, Gege",
      "Alan Moore, Frank Miller, Todd McFarlane",
      "Backderf, Derf",
      "CHARLIER - GIRAUD",
      "Charlie Adlard / Robert Kirkman",
      "Davis, Jim",
      "De Saint-Exupery, Antoine",
      "Flor M. Salvador",
      "GEGE AKUTAMI",
      "Gerry Duggan",
      "Hiromu Arakawa",
      "Joe, Hill",
      "Jonathan Hickman",
      "Kentaro Miura",
      "MARK RUSSELL - MIKE ALLRED.",
      "Quino",
      "Sankichi Hinodeya",
      "Toriyama, Akira",
      "Viplajo",
      "Yuhki Kamatani"
    ],
    "publishers": []
  },
  "idiomas-aprendizaje": {
    "authors": [
      "Border Rosemary",
      "Campbell Metcalf Y Otros",
      "Caron, Jean Luc/ Lebrun, Sandra",
      "Daphne Paizee",
      "Edwards, Lynda",
      "Falla, Tim",
      "GARCIA NEGRONI , MARIA MARTA",
      "Hastings, Bob",
      "Jones, Daniel",
      "Ladybird",
      "Latham-Koenig, Christina",
      "MURPHY, Raymond",
      "McCarthy, Michael",
      "NATIONAL GEOGRAPHIC LEARNING",
      "Nick KENNY",
      "Paul Korky / Thomas Valerie",
      "Read, Carol",
      "Sheila Dignen - Lynda Edwards",
      "Spencer, David",
      "Thompson, Tamzin"
    ],
    "publishers": []
  },
  "filosofia-ciencias-sociales": {
    "authors": [
      "Alejandro Peña Esclusa",
      "Arendt, Hannah",
      "Bachelard, Gaston",
      "Butler, Judith",
      "Carballeda, Alfredo Juan Manuel",
      "Carla Delladonna, Rocío Uceda",
      "David Dorfman / Armand Mattelart",
      "Donald Robertson",
      "HOPPE HANS",
      "ITUARTE TELLAECHE, AMAYA",
      "JOHN KENNETH GALBRAITH",
      "Juan Miguel Zunzunegui",
      "León Tolstói",
      "Mariano Perez Carrasco",
      "Massimo Pigliucci y Gregory Lopez",
      "Nietzsche, Friedrich",
      "Pablo d Ors",
      "Ruocco, Juan",
      "Sayak Valencia",
      "Segato Rita Laura",
      "Stanley, Jason"
    ],
    "publishers": []
  },
  "medicina-salud": {
    "authors": [
      "A. I. Kapandji",
      "ALBA PADRO",
      "Alejandro Scicolone",
      "Alonso - Esquisabel",
      "Ana Maria Soprano",
      "Andrea Taddei",
      "Andreas Ludwig Kalcker",
      "Belaustegui, Isabel",
      "CATHERINE DOLTO",
      "CUETOS VEGA, Fernando",
      "Cabezuelo Gloria",
      "DRAKE, Richard",
      "Danièle Flaumenbaum",
      "Doctor Bayter",
      "Elizabeth Navarro",
      "García Merletti",
      "Glockler - Schurholz",
      "Gonzalez",
      "HAEBERLE, ERWIN",
      "Helen S. Kaplan",
      "Jesus Seco",
      "Joaquín Costa Subias & Juan Alfonso Soria Jerez",
      "LATTIN, DON",
      "Maggio Veronica",
      "Mara Liz Serra",
      "Mendoza Lara, Elvira",
      "Merce Marbes",
      "Michael Schuler",
      "Michel Odent",
      "Nayar, Ritu",
      "Noriega, Pablo",
      "Pablo Sanjurjo Crespo y ANTONIO BALDELLOU",
      "Roberto C. Frenquelli",
      "Rogers, Sally J",
      "SATI",
      "SEARS BARRY",
      "Torralva, Teresa",
      "Valls, Carme"
    ],
    "publishers": []
  },
  "ciencia-tecnologia": {
    "authors": [
      "AUDESIRK, TERESA",
      "BOARD, Jon & CROSS, Alan",
      "Bruice, Paula Yurkanis",
      "Derek B. Lowe",
      "Dr. Chris Colles",
      "FONT ROVIRA, FRANCESC",
      "Federico Kukso",
      "García Bocanegra. Ignacio",
      "Grinberg-Zylberbaum, Jacobo",
      "Gustavo Eduardo D'Elia",
      "Jose Colera Jimenez",
      "LOPESINO CORRAL, JORDI",
      "MATTHES, ERIC",
      "Margulis, Lynn",
      "ROBERT SAPOLSKY",
      "Raymond Chang - Jason Overby",
      "Raúl Rivas",
      "Ron Larson",
      "SANZ TIMON, JOSE MANUEL",
      "Sears / Zemansky / Young / Freedman",
      "URRESTARAZU GAVILAN, MIGUELá"
    ],
    "publishers": []
  },
  "historia": {
    "authors": [
      "Alejandro Dumas",
      "Ana Maria Cabrera",
      "Dominique Lapierre / Larry Collins",
      "EDMUNDO WERNICKE",
      "Francis Bond Head",
      "GILLES PERRAULT",
      "Gloria Delgado",
      "Gordon Thomas",
      "Guilhem Olivier",
      "Ian Kershaw",
      "Ilan Pappe",
      "Jose M. Gutierrez De La Camara Señan",
      "Kraus, Otto B.",
      "LAPIERRE, DOMINIQUE",
      "Michael H. Kater",
      "Raymond Cartier",
      "SABORIDO JORGE"
    ],
    "publishers": []
  },
  "derecho": {
    "authors": [
      "Jakobs, Günther",
      "Manzanero, Antonio Lucas"
    ],
    "publishers": []
  },
  "cocina-gastronomia": {
    "authors": [
      "Aleja Díaz",
      "Betular, Damian",
      "Luisina Troncoso",
      "Phaidon Editors",
      "Roca Paulina"
    ],
    "publishers": []
  }
};

// ─── Palabras/frases distintivas por categoría (independientes de autor) ───
// Regla: nunca una sola palabra genérica corta decide sola — cada entrada acá
// es una frase de 2+ palabras, o una palabra suficientemente específica
// (ej. "tarot", "biblia", "manga") que casi no aparece fuera de su rubro.
// Se buscan como substring dentro del título normalizado (sin acentos, en
// minúscula). Confianza más baja que un autor reconocido (ver classify.js).
export const KEYWORD_SIGNALS = {
  'esoterismo-tarot': [
    'tarot', 'oraculo', 'oraculos', 'cartas oraculo', 'runas', 'wicca',
    'brujeria', 'chamanismo', 'astrologia', 'horoscopo', 'cabala mistica',
    'grimorio', 'hechiceria', 'numerologia', 'quiromancia', 'yoga',
    'meditacion',
  ],
  'religion-espiritualidad': [
    'biblia', 'evangelio', 'nuevo testamento', 'antiguo testamento',
    'catecismo', 'teologia', 'iglesia catolica', 'espiritualidad cristiana',
    'sagrada escritura', 'salmos', 'reina valera',
  ],
  'infantil-juvenil': [
    'cuento infantil', 'cuentos infantiles', 'para ninos', 'para niños',
    'libro infantil', 'colorear', 'para colorear', 'primera infancia',
    'juvenil', 'young adult', 'cuento', 'cuentos',
  ],
  'comics-manga': [
    'manga', 'comic', 'cómic', 'novela grafica', 'novela gráfica', 'historieta',
  ],
  'cocina-gastronomia': [
    'receta', 'recetas', 'cocina', 'gastronomia', 'gastronomía', 'reposteria',
    'pasteleria', 'culinari',
  ],
  'idiomas-aprendizaje': [
    'workbook', "student's book", 'grammar in use', 'phrasal verbs',
    'english file', 'aprender ingles', 'aprender inglés', 'diccionario ingles',
    'cambridge english', 'gramatica inglesa', 'diccionario',
  ],
  'medicina-salud': [
    'medicina interna', 'anatomia', 'anatomía', 'fisiologia', 'fisiología',
    'farmacologia', 'farmacología', 'clinica medica', 'manual clinico',
    'enfermeria', 'nutricion clinica', 'pediatria', 'cardiologia',
    'trastorno', 'trastornos', 'psicomotricidad', 'autismo', 'embarazo',
    'ansiedad', 'tdah', 'depresion', 'depresión', 'abuso sexual', 'atlas',
  ],
  'psicologia': [
    'psicoanalisis', 'psicoanálisis', 'psicoterapia', 'terapia cognitiva',
    'psicologia clinica', 'trastorno de ansiedad', 'psicologia del desarrollo',
  ],
  'derecho': [
    'derecho penal', 'derecho civil', 'codigo civil', 'código civil',
    'derecho procesal', 'jurisprudencia',
  ],
  'negocios-economia': [
    'marketing', 'finanzas personales', 'emprendimiento', 'negociacion',
    'liderazgo empresarial', 'management', 'estrategia de negocios',
  ],
  'ciencia-tecnologia': [
    'programacion', 'programación', 'quimica organica', 'quimica general',
    'fisica universitaria', 'biologia molecular', 'matematica universitaria',
    'calculo diferencial', 'matematica', 'matemática',
  ],
  'historia': [
    'segunda guerra mundial', 'primera guerra mundial', 'historia de uruguay',
    'historia argentina', 'revolucion rusa', 'historia contemporanea',
    'memorias', 'biografia', 'biografía',
  ],
  'arte-diseno-fotografia': [
    'diseño grafico', 'diseno grafico', 'fotografia', 'historia del arte',
    'ilustracion', 'ilustración',
  ],
  'filosofia-ciencias-sociales': [
    'filosofia', 'filosofía', 'sociologia', 'antropologia', 'ciencia politica',
    'teoria critica', 'ensayo',
  ],
  'educacion': [
    'pedagogia', 'pedagogía', 'didactica', 'nivel inicial', 'formacion docente',
    'montessori', 'crianza',
  ],
  'literatura-ficcion': [
    'novela', 'teatro',
  ],
  'desarrollo-personal': [
    'duelo', 'mindfulness',
  ],
};

// ─── Señales de "no es un libro" ───────────────────────────────────────────
// Ampliado desde la lista original de BestsellerSection.astro (24 términos,
// probado insuficiente en CF-CATEGORÍAS-IA-DIAGNÓSTICO: solo detectaba 5 de
// 200 objetos reales) con lo aprendido clasificando a mano ~600 casos reales
// en CF-CATEGORÍAS-0B/0C: discos, merchandising con licencia, juegos de mesa,
// papelería, joyería, antigüedades.
export const OBJECT_SIGNALS = [
  // Antigüedades y decoración (lista original ampliada)
  'cruz', 'crucifijo', 'bronce', 'chapa esmaltada', 'cartel chapa', 'dije',
  'plata 925', 'jaspe', 'colgante vintage', 'sacapuntas vintage',
  'candelabro', 'figura bronce', 'figuras bronce', 'decorativo', 'decorativa',
  'pared cristo', 'cristo inri', 'inri antigua', 'jeringa',
  'veterinaria vidrio', 'volante cine', 'antiguo matrimonio',
  'antigua veterinaria', 'pieza antigua', 'objeto antiguo', 'medalla',
  'moneda antigua', 'estampilla', 'sello postal', 'reloj antiguo',
  'llavero antiguo', 'gemelos antiguo', 'insignia', 'uniforme antiguo',
  'espada', 'daga', 'miniatura decorativo', 'maquina de escribir',
  'radio antigua', 'camara fotografica antigua', 'automobilia',
  'matricula vintage', 'matricula antigua', 'postales antiguas',
  'plato limoges', 'porcelana', 'ceramica antigua', 'pesas antiguas',
  'prendedor plata', 'anillo plata 925',
  // Música / medios físicos — no detectados en la primera pasada. Se evita
  // un "cd" suelto de 2 letras: matchearía como substring dentro de
  // cualquier palabra que lo contenga (ver rules.test.js).
  'vinilo', 'lp remasterizado', 'disco cd', 'cd fisico', 'edicion cd',
  'cd para coleccion',
  // Merchandising / juguetes / papelería
  'cartuchera', 'estuche de cosmeticos', 'estuche de maquillaje',
  'vincha tiara', 'kit de ganchillo', 'kit de crochet', 'flashcards',
  'agenda 20', 'planner', 'expansion juego de mesa', 'juego de mesa',
  'adhesivos', 'lote de revistas', 'revista coleccionista',
  'fasciculo coleccionable',
];

// Umbral de fan-out para considerar un rasgo "genérico" en vez de específico
// de una categoría — usado por classify.js al validar coincidencias débiles.
export const MIN_KEYWORD_LENGTH = 4;
