name = "amado-cover-index-preview"
main = "cover-index-preview.js"
compatibility_date = "2024-09-23"
workers_dev = true

[[r2_buckets]]
binding = "PRODUCTION_COVERS_READONLY"
bucket_name = "amadolibros-images-production"

[[r2_buckets]]
binding = "ISOLATED_INDEX_PREVIEW"
bucket_name = "amadolibros-images-preview"
