name = "amado-cover-resource-preview"
main = "cover-resource-preview.js"
compatibility_date = "2024-09-23"
workers_dev = true

[[r2_buckets]]
binding = "PRODUCTION_COVERS_READONLY"
bucket_name = "amadolibros-images-production"
